name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -C main ./gotest.go

    - name: Print Version
      run: main/gotest > VERSION

    - uses: actions/upload-artifact@v3
      with:
        name: Upload Artifacts
        path: |
          main/gotest
          VERSION