name: Go Releaser

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        version: latest
        args: release --clean --snapshot --skip=sign

    - name: LS
      run: ls -lR > LS

    - uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: |
          dist/
          LS
