name: Upload Test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/upload-artifact@v3
      with:
        name: TEST
        path: LICENSE