name: Variables

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Create File
      run: date > V1

    - uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: |
          V1
